# Generated by Django 4.2.28 on 2026-06-19 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSyncConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=255)),
                ('sync_mode', models.CharField(choices=[('manual', 'Manual Mode (Refresh Button Only)'), ('schedule_5m', 'Every 5 Minutes'), ('schedule_1h', 'Every 1 Hour'), ('schedule_1d', 'Every 1 Day'), ('schedule_30d', 'Every 30 Days'), ('event', 'Event Mode (On INSERT/UPDATE/DELETE)'), ('hybrid', 'Hybrid Mode (Event + 24h Verification)')], default='manual', max_length=20)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('next_sync_expected', models.DateTimeField(blank=True, null=True)),
                ('rows_count', models.IntegerField(default=0)),
                ('last_change', models.DateTimeField(blank=True, null=True)),
                ('client_devices', models.IntegerField(default=0)),
                ('database_calls_saved', models.BigIntegerField(default=0)),
                ('bandwidth_saved_mb', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DeveloperProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('key', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
