# Generated by Django 4.2.9 on 2026-06-22 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='syncevent',
            new_name='dashboard_s_project_011271_idx',
            old_name='sf_syncevent_project_idx',
        ),
        migrations.RenameIndex(
            model_name='syncevent',
            new_name='dashboard_s_table_c_0c658a_idx',
            old_name='sf_syncevent_table_idx',
        ),
        migrations.AddField(
            model_name='tablesyncconfig',
            name='avg_response_time_ms',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='tablesyncconfig',
            name='cache_hits',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablesyncconfig',
            name='cache_misses',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablesyncconfig',
            name='total_requests',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(blank=True, help_text='DEPRECATED: Legacy plaintext key. Do not use for new keys.', max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key_prefix',
            field=models.CharField(blank=True, help_text='First 18 chars of the raw key — displayed in dashboard only.', max_length=20),
        ),
        migrations.AlterField(
            model_name='tablesyncconfig',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='tablesyncconfig',
            name='version_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
