# Generated by Django 4.2.28 on 2026-06-19 17:10

import dashboard.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='tablesyncconfig',
            options={'ordering': ['table_name']},
        ),
        migrations.RemoveField(
            model_name='apikey',
            name='user',
        ),
        migrations.RemoveField(
            model_name='developerprofile',
            name='company_name',
        ),
        migrations.AddField(
            model_name='apikey',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='last_used',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(default=dashboard.models._generate_api_key, max_length=80, unique=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(default='Default Key', max_length=100),
        ),
        migrations.AlterField(
            model_name='developerprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tablesyncconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tablesyncconfig',
            name='sync_mode',
            field=models.CharField(choices=[('manual', 'Manual — Refresh Button Only'), ('schedule_5m', 'Schedule — Every 5 Minutes'), ('schedule_1h', 'Schedule — Every 1 Hour'), ('schedule_1d', 'Schedule — Every 1 Day'), ('schedule_30d', 'Schedule — Every 30 Days'), ('event', 'Event — On INSERT / UPDATE / DELETE'), ('hybrid', 'Hybrid — Event + 24h Verification')], default='manual', max_length=20),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='apikey',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='dashboard.project'),
        ),
        migrations.AddField(
            model_name='tablesyncconfig',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='table_configs', to='dashboard.project'),
        ),
        migrations.AlterUniqueTogether(
            name='tablesyncconfig',
            unique_together={('project', 'table_name')},
        ),
        migrations.RemoveField(
            model_name='tablesyncconfig',
            name='user',
        ),
    ]
