# Generated by Django 4.2.9 on 2026-06-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_sf_syncevent_project_idx_dashboard_s_project_011271_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablesyncconfig',
            name='version_number',
        ),
        migrations.AddField(
            model_name='tablesyncconfig',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tablesyncconfig',
            name='cache_version',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tablesyncconfig',
            name='compression',
            field=models.CharField(choices=[('none', 'No Compression'), ('lz4', 'LZ4 (Fast)'), ('zstd', 'Zstandard (High Ratio)'), ('gzip', 'GZIP')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='tablesyncconfig',
            name='encryption',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tablesyncconfig',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='tablesyncconfig',
            name='refresh_interval',
            field=models.IntegerField(default=0, help_text='Refresh interval in minutes (0 = event only)'),
        ),
        migrations.AddField(
            model_name='tablesyncconfig',
            name='storage_mode',
            field=models.CharField(choices=[('ram_only', 'RAM Only'), ('ram_disk', 'RAM + Disk Persistent'), ('disabled', 'Disabled (Direct DB)')], default='ram_disk', max_length=20),
        ),
    ]
