# Generated by Django 4.2.9 on 2026-06-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_tablesyncconfig_version_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablesyncconfig',
            name='client_devices',
        ),
        migrations.RemoveField(
            model_name='tablesyncconfig',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='tablesyncconfig',
            name='last_change',
        ),
        migrations.RemoveField(
            model_name='tablesyncconfig',
            name='next_sync_expected',
        ),
        migrations.AddField(
            model_name='project',
            name='project_prefix',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
    ]
