# Generated by Django 4.2.9 on 2026-06-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_tablesyncconfig_client_devices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablesyncconfig',
            name='duplicates_prevented',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tablesyncconfig',
            name='timeout',
            field=models.IntegerField(blank=True, help_text='Cache timeout in seconds. None means no expiry.', null=True),
        ),
    ]
