# Generated by Django 4.2.9 on 2026-06-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_tablesyncconfig_duplicates_prevented_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key_prefix',
            field=models.CharField(blank=True, help_text='The full raw key — displayed in dashboard.', max_length=100),
        ),
    ]
