# Generated by Django 4.2.9 on 2026-06-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_apikey_key_prefix'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tablesyncconfig',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='tablesyncconfig',
            name='table_name',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
