# Generated by Django 4.2.9 on 2026-06-25 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_tablesyncconfig_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('refresh', 'Sync Refresh'), ('create_table', 'Table Created'), ('delete_table', 'Table Deleted'), ('new_api', 'API Key Generated'), ('update_version', 'Version Updated')], max_length=20)),
                ('details', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='dashboard.project')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
